### ISSUE TITLE
Old version on pypi does not build with Python 3.7

### ISSUE THREAD

**Issue by dotlambda** [snowballstem/pystemmer#18]
```
src/Stemmer.c: In function '__Pyx_GetException':
src/Stemmer.c:3222:24: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'; did you mean 'curexc_type'?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
src/Stemmer.c:3223:25: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'; did you mean 'curexc_value'?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
src/Stemmer.c:3224:22: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
src/Stemmer.c:3225:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'; did you mean 'curexc_type'?
     tstate->exc_type = local_type;
             ^~~~~~~~
             curexc_type
src/Stemmer.c:3226:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'; did you mean 'curexc_value'?
     tstate->exc_value = local_value;
             ^~~~~~~~~
             curexc_value
src/Stemmer.c:3227:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
     tstate->exc_traceback = local_tb;
             ^~~~~~~~~~~~~
             curexc_traceback
src/Stemmer.c: In function '__Pyx_ExceptionSave':
src/Stemmer.c:3250:21: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'; did you mean 'curexc_type'?
     *type = tstate->exc_type;
                     ^~~~~~~~
                     curexc_type
src/Stemmer.c:3251:22: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'; did you mean 'curexc_value'?
     *value = tstate->exc_value;
                      ^~~~~~~~~
                      curexc_value
src/Stemmer.c:3252:19: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
     *tb = tstate->exc_traceback;
                   ^~~~~~~~~~~~~
                   curexc_traceback
src/Stemmer.c: In function '__Pyx_ExceptionReset':
src/Stemmer.c:3264:24: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'; did you mean 'curexc_type'?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
src/Stemmer.c:3265:25: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'; did you mean 'curexc_value'?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
src/Stemmer.c:3266:22: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
src/Stemmer.c:3267:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'; did you mean 'curexc_type'?
     tstate->exc_type = type;
             ^~~~~~~~
             curexc_type
src/Stemmer.c:3268:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'; did you mean 'curexc_value'?
     tstate->exc_value = value;
             ^~~~~~~~~
             curexc_value
src/Stemmer.c:3269:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
     tstate->exc_traceback = tb;
             ^~~~~~~~~~~~~
             curexc_traceback
error: command 'gcc' failed with exit status 1
```

**Comment by dotlambda** [comment]
I'm using Cython 0.28.3, which according to https://github.com/cython/cython/issues/1955 should not generare this error. I can also confirm that the error still appears when using Cython's latest git head.

**Comment by felixonmars** [comment]
Cython build was skipped if the resulting C file is present. Just removing src/Stemmer.c before building fixes the build for me.

**Comment by felixonmars** [comment]
Since it's a clean build, I assume it comes from the PyPI tarball.

**Comment by ojwb** [comment]
> Since it's a clean build, I assume it comes from the PyPI tarball.

Ah - you'll need to talk to @rboulton about that.

**Comment by vishwin** [comment]
We are [tracking this in FreeBSD](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=229629). In my tests with Python 3.7 and cython 0.28.2, as long as `setup.py` can import `Cython`, the pre-existing `src/Stemmer.c` (from PyPi) is overwritten. The build then succeeds.

It may be beneficial to include `cython` in `setup_requires` and do away with the conditional check completely in `setup.py`.

**Comment by zurk** [comment]
Thanks, @vishwin for your insight! 
I was able to fix this issue just installing cython: `pip3 install cython`.

**Comment by ojwb** [comment]
So in simple terms, install cython and the pypi package works fine with Python 3.7.

>  It may be beneficial to include `cython` in `setup_requires` and do away with the conditional check completely in `setup.py`.

@vishwin I'm not really a Python coder, but assuming that's not a controversial approach can you provide a patch?

We could still do with @rboulton handing on the PyPI package to a new maintainer as it's not been updated for over 5 years and the bundled libstemmer version is really ancient.  Anyone on this thread interested in taking on that role?

Seems pinging Richard via github isn't getting his attention so I'll try to contact him by other means.

**Comment by ojwb** [comment]
I've made contact with @rboulton and he's happy to hand over maintainership of the PyPI package if someone's up for taking that on - meanwhile he's going to try to find time to update the current package.

**Comment by zurk** [comment]
@ojwb , @rboulton I do not who is maintainer right now, but I PR a fix for Python 3.7 problem:
https://github.com/snowballstem/pystemmer/pull/21
Please take a look.

**Comment by zurk** [comment]
@ojwb, @rboulton. Friendly 10 days ping, guys.

**Comment by zurk** [comment]
Yeah, but can we merge the fix to make things work for Python 3.7 while we do not have a suitable C libstemmer version? The fix always compiles Cython code, so no need in C.

**Comment by zurk** [comment]
Ok guys, on behalf of source{d} we are going to fork pystemmer and maintain it by ourselves.

**Comment by jg-you** [comment]
Any update on this? 2.18.1.0 won't install on 3.7 due to Cython mistakes.

     pystan/_misc.cpp: In function ‘void __Pyx__ExceptionSave(PyThreadState*, PyObject**, PyObject**, 
PyObject**)’:
     pystan/_misc.cpp:18735:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     *type = tstate->exc_type;

**Comment by TTRh** [comment]
is the fork a public repo @zurk ?

**Comment by zurk** [comment]
well, in the end, we have not done it, but you can use my fork with a fix https://github.com/zurk/pystemmer

**Comment by ojwb** [comment]
Well, the repo is updated to use the recently release Snowball 2.0.0.

@rboulton Can you update PyPI?

A new maintainer is really still needed, but then at least things will be in a decent state.

**Comment by ojwb** [comment]
I've now also dealt with the open PRs and done some clean up.

We were using `epydoc` to produce HTML versions of the docs, but that's been dead over a decade now so I stripped out mentions and support in bdff76cdb40df4383e8eb5bf6117e6ce98d7c33b.  Probably there's something else to use instead, but I'm not sure what (sphinx perhaps?)

Pending an update to PyPI people can at least now install from the git repo using:

```
pip install git+git://github.com/snowballstem/pystemmer
```

**Comment by Desklop** [comment]
@ojwb in the current state of the repository, in order to assemble the package, you must first install Cython. I made a [pull request](https://github.com/snowballstem/pystemmer/pull/26) that will save users from pre-installing Cython :)

**Comment by DomHudson** [comment]
Any update on getting this pushed to pypi? The version available there contains `PyStemmer-1.3.0/src/Stemmer.c` which does not build.

**Comment by ojwb** [comment]
@DomHudson We still don't have a new pypi maintainer to hand over to. I've not heard from @rboulton but I'm guessing he hasn't found the time to make an update.

**Comment by felixonmars** [comment]
@ojwb @rboulton In case a maintainer is still needed, I can do that. My PyPI username is: felixonmars

**Comment by ojwb** [comment]
That sounds good - thanks for offering.  You'll need to coordinate with @rboulton about the pypi handover as he's the current maintainer there.  If he doesn't respond let me know and I can get someone to prod him via SMS.

Are you interested in taking over PyStemmer entirely?

As I said on the mailing list recently, we don't try to support bindings to the C stemmer from any other languages under the snowballstem,org umbrella, and it's only for historical reasons that PyStemmer is under it.  With limited resources I think it makes more sense to focus snowballstem.org efforts on the algorithms and the compiler.

**Comment by rboulton** [comment]
Happy to add you to the project on pypi so you can make a release; I've added you for now as a maintainer, but if you're interested in taking over entirely, I can add you as an "owner" role.

**Comment by felixonmars** [comment]
I am actually packaging both snowballstemmer & pystemmer for Arch so I would need to maintain it anyway. Perhaps I should stay as a maintainer for now :)

**Comment by felixonmars** [comment]
I have uploaded PyStemmer-2.0.0.1 to pypi and updated on Arch accordingly. Please let me know if it's solved now :)

<del>Made a stupid mistake for 2.0.0 so I added another .1 for a quick fix, nothing else was changed</del>

**Comment by DomHudson** [comment]
Thank you! It does build now but I do have to manually install Cython first as the setup.py does a direct import. Ideally, the setup.py would work out of the box with just `pip install pystemmer`. Happy to contribute to this if desired!

I'm interested in why this is a major increase to `2.0.0` is it backwards incompatible - has the underlying stemmer algorithm/output changed? Should I pin my company's projects to 1.3.0 - they rely on the output of the stemmer remaining the same.

Side note, ideally we should stick to [semver](https://semver.org/) so the patched version should really be `2.0.1` otherwise it's not clear what the individual numbers indicate.

Thanks for pushing this up!

**Comment by felixonmars** [comment]
The major version increase should be in sync with the underlying libstemmer C library. It seems @ojwb changed setup.py to always require Cython intentionally. If someone would change it back I can also make manylinux wheels that can take advantage of this.

**Comment by ojwb** [comment]
If you want to propose a change, please open a PR.  I'm unclear exactly what you're wanting reverted, and a PR shows me much more clearly than trying to guess the commit (my best guess is b29ce2109f49c0b82517fa9d3e2bbacc1f8b34ec which was part of PR #21, so was intentional - shipping the C files generated by pyrex wasn't working out so well because the older generated files were incompatible with Python 3.7 ... but that wasn't a change made by me, so maybe you mean something else.)

Getting Cython installed automatically if a suitable version isn't already installed would be good, but is beyond my knowledge of this stuff (TBH, I'd expect `'Cython>=0.28.5,<1.0'` in `setup_requires` to achieve that, but it seems it doesn't).  Someone submitted #26 but that looks to me like it will ALWAYS install Cython from pip, even if the user has a suitable cython already installed, which seems undesirable.  The submitter hasn't responded to my query about that so that one's stalled currently.

**Comment by ojwb** [comment]
> I'm interested in why this is a major increase to 2.0.0 is it backwards incompatible - has the underlying stemmer algorithm/output changed?

The "1.3.0" version is over 7 years old, and some algorithms have changed since - in fairly minor ways, but you'll probably want to reindex after upgrading to avoid problems.  Snowball hasn't formally adopted semver currently, but the 2.0.0 was partly chosen to flag this up.  It's also the first release as "snowballstem.org" and after Martin Porter retired.

> Should I pin my company's projects to 1.3.0 - they rely on the output of the stemmer remaining the same.

I wouldn't pin to 1.3.0 indefinitely - the changes were all made with good reasons, and we can't support people using 7+ year old versions.  You might want to until you get a suitable time to upgrade though.

**Comment by DomHudson** [comment]
Thanks for your response @ojwb  I have submitted a PR that will get Cython installed automatically if a suitable version isn't already installed. 
Many thanks,
Dom

**Comment by ojwb** [comment]
Thanks for that.

The issue actually reported here (i.e. "Old version on pypi does not build with Python 3.7") was fixed by pypi getting updated to 2.0.0.  The side issue of needing a new pypi maintainer is sorted to, while the other issue raised of Cython requirements is covered by the PR, so I'm closing this now.
